# Simple workflow for deploying static content to GitHub Pages
name: push latest changes to production repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['production']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  update_parent_repos: # push latest change to parent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parent_repo: [Keywords-AI-Landing-Production]

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: Keywords-AI/${{ matrix.parent_repo }}
          token: ${{ secrets.KA_LANDING }}
          submodules: 'recursive'
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
